const DEFAULT_BOT_PREFIX = '%'
const DEFAULT_IMPRESSIONS = 'true'
const DEFAULT_VOICE = 'true'
const DEFAULT_MENTIONS = 'true'
const DEFAULT_SENSITIVITY = '0.45'

module.exports = {
  DEFAULT_BOT_PREFIX: DEFAULT_BOT_PREFIX,
  DEFAULT_IMPRESSIONS: DEFAULT_IMPRESSIONS,
  DEFAULT_VOICE: DEFAULT_VOICE,
  DEFAULT_MENTIONS: DEFAULT_MENTIONS,
  DEFAULT_SENSITIVITY: DEFAULT_SENSITIVITY
}
